

name: rebrand_cli
description: Rebrand Flutter apps from one CLI. Rename app/package IDs, update labels, and generate launcher icons plus native splash screens with Android 12 support.
version: 3.0.1
environment:
  sdk: ^3.10.3

dependencies:
  path: ^1.8.3
  image: ^4.0.0

executables:
  rebrand: rebrand

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6


homepage: https://github.com/sanam-tamang/rebrand_cli
repository: https://github.com/sanam-tamang/rebrand_cli